### ISSUE TITLE
[2024.08.26~2024.09.01] 곽다희 주간 회고

### ISSUE THREAD

**Issue by daadaadaah** [daadaadaah/reviewStudy#156]
# 이번주 목표
- [x] 목표 1. 주 3일 9시 일어나서 무언가 하기
   - [x] 월 : 병출로 성공!
   - [ ] 화 : 10시 일상 시작
   - [ ] 수 : 3~4시 취침으로...11시에 기상....일찍 자자...
   - [x] 목 : 카출로 성공! -> 죽이되는 밥이되는 12시안에 무조건 침대에 누워야되는것 같다!
   - [ ] 금 : 3시 취침으로 10시 기상.... 
   - [x] 토 : 카출로 성공! 
   - [ ] 일
- [x] 목표 2. 헬출 주4일
   - [x] 월 : 헬출!
   - [ ] 화
   - [x] 수 : 헬출!
   - [ ] 목
   - [x] 금 : 헬출! 유산소 
   - [x] 토 : OT
   - [ ] 일 : 유산소 예정
- [ ] 목표 3. 단백질 90g 먹기
   - [x] 월 : 95g -> 5g(달걀)+36g(불고기)+20g(단백질 음료)+14g(제육김밥)+20g(단백질 음료)
   - [x] 화 : 98g-> 5g(달걀)+7g(두유)+14g(제육김밥)+20g(단백질 음료)+36g(불고기)+7g(그릭요거트 100g)+10g(땅콩버터 50g) 
   - [ ] 수 : 85g -> 5g(달걀)+5g(그릭요거트)+10g(땅콩버터)+30g(단백질 음료)+10g(키토김밥)+15g(뼈해장국 1/2그릇)+10g(땅콩버터)
   - [x] 목 : 94g -> 5g(달걀)+5g(그릭요거트)+10g(땅콩버터)+30g(단백질 음료)+15g(제육쌉밥)+15g(뼈해장국 1/2그릇)+7g(두유)+7g(치즈케익)
   - [ ] 금 : 60g -> 5g(달걀)+5g(그릭요거트)+10g(땅콩버터)+7g(제육쌉밥1/2)+12g(막국수)+20g(단백질 음료)
   - [x] 토 : 93g -> 5g(달걀)+13g(생선)+5g(제육볶음 1/3)+30g(단백질 음료)+40g(돼지갈비)
   - [ ] 일
- [ ] 목표 4. 주간 회고 스케줄러 
  - [ ] 주요 개선 포인트 정리
       - [ ] 순환 참조 문제 해결 정리 -> 아이패드로 시각화 마무리 작업
       - [x] 디스코드 개선점 1. 저장 실패 데이터 전송 방식 변경 정리 ([관련 링크](https://github.com/daadaadaah/review-study-app/issues/79))
       - [x] 디스코드 개선점 2. 알림 주기 변경 정리 ([관련 링크](https://github.com/daadaadaah/review-study-app/issues/78))
       - [ ] 기타 개선점 정리
       - [ ] 수작업 대비 n배 향상 내용 정리
       - [x] 비동기 및 싱글 스레드로 비즈니스 로직과 부가 기능 로직 간의 장애 전파 문제, 동시성 문제 해결 및 성능 최적화([관련 링크](https://github.com/daadaadaah/review-study-app/issues/80))
- [x] 목표 5. 이력서 제출

# 회고
## 1. 목표 1에 대한 회고
- 드디어 1회 성공했습니다! 이력서 마감일은 저를 움직이게 하네요ㅎㅎ
- 성공하면서 느낀 점은 숙면하려면 운동으로 땀을 쫌 빼야 한다와 12시 전에 무슨일이 있더라도 자야지 그나마 1~2시에 잠든다는 것입니다.
- 다음주에도 한번 또 성공해보겠습니다!

## 2. 목표 2에 대한 회고
- 헬출이 다소 소홀해져서 목표로 설정했는데, 다행히 성공했습니다.
- 잠을 위해, 정신 건강을 위해 헬출 주4회 계속 도전해보겠습니다.

## 3. 목표 3에 대한 회고
- 먹을 때 마다 계속 기록하니, 성취감도 있고 좋네요!
- 일요일은 저에게 상을 주기 위해 먹고 싶은거 마음꺼 먹어서 생략했습니다.
- 올해 안에 근육 24kg 목표인데, 단백질 열심히 먹어보겠습니다!ㅎㅎ

## 4. 목표 4에 대한 회고
- 일단 큰 정리는 끝났습니다.
- 이 내용을 어떻게 블로그 또는 포트폴리오에 녹여낼지 고민해봐야겠어요!
- 테스트 코드도 작성해봐야겠죠...ㅎㅎ 

## 5. 목표 5에 대한 회고
- (오늘 저녁에 제출하면 성공) 

# 다음주 목표
목표 1. 주 3일 9시 일어나서 무언가 하기
목표 2. 헬출 주4회
목표 3. 단백질 90g 주 5회 먹기
목표 4. 주간 회고 스케줄러 마무리하기 -> 시간 남으면, JPA 게시판 도전??
목표 5. 포트폴리오 또는 경력기술서 작성 -> 이력서에는 큰 타이틀만 남겨주고, 자세한 내용은 포트폴리오나 경력기술서 작성하기
